// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxTgYuTBA0JFDEypvTBEfaHjIXNCRqIM',
    appId: '1:987620378448:android:cb9efcf52816f5353a4e55',
    messagingSenderId: '987620378448',
    projectId: 'mi-partner-app',
    databaseURL: 'https://mi-partner-app-default-rtdb.firebaseio.com',
    storageBucket: 'mi-partner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6vFODegMqMyenjL8uATmmLCQiN3A8p4',
    appId: '1:987620378448:ios:6d8aa889f00ccdff3a4e55',
    messagingSenderId: '987620378448',
    projectId: 'mi-partner-app',
    databaseURL: 'https://mi-partner-app-default-rtdb.firebaseio.com',
    storageBucket: 'mi-partner-app.appspot.com',
    androidClientId: '987620378448-tb196skf4cvsnthapbkgg5vpebnojj50.apps.googleusercontent.com',
    iosClientId: '987620378448-nh6t0h1v43cgart7h4auh47hpctt5rgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.miPartnerApp',
  );
}
